services:
    api:
        image: registry.sepradc.ovh/charge/api:arm64
        platform: linux/arm64
        restart: unless-stopped
        depends_on:
            - db
        volumes:
          - caddy_data:/data
          - caddy_config:/config
        environment:
            APP_ENV: prod
            SERVER_NAME: "http://php:80"
            CADDY_GLOBAL_OPTIONS: |
              auto_https off
            APP_UID: ${APP_UID:-1000}
            CORS_ALLOW_ORIGIN: "^(https?://(?:.+\\.)?${HOST}(?::\\d{1,5})?)$$"
            DATABASE_URL: ${DATABASE_URL}
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:2019/metrics"]
            interval: 30s
            timeout: 10s
            retries: 3
            start_period: 60s
        labels:
            - "traefik.enable=true"
            - "traefik.docker.network=sepradcnetwork"
            # Middlewares spécifiques à charges-website
            - "traefik.http.middlewares.charges-force-https.redirectscheme.scheme=https"
            - "traefik.http.middlewares.charges-force-https.redirectscheme.permanent=true"
            - "traefik.http.middlewares.charges-rewrite-api.stripprefix.prefixes=/api"
            - "traefik.http.middlewares.charges-rewrite-api.stripprefix.forceslash=false"
            # http://${HOST} : Redirect to https
            - "traefik.http.routers.charges-api.rule=Host(`${HOST}`) && (PathPrefix(`/api/`) || PathPrefix(`/admin`) || PathPrefix(`/bundles/`)  || PathPrefix(`/images/`))"
            - "traefik.http.routers.charges-api.entrypoints=web"
            - "traefik.http.routers.charges-api.priority=100"
            - "traefik.http.routers.charges-api.middlewares=charges-force-https"
            - "traefik.http.routers.charges-api.service=charges-api"
            - "traefik.http.services.charges-api.loadbalancer.server.port=80"
            # https://${HOST}
            - "traefik.http.routers.charges-api-tls.rule=Host(`${HOST}`) && (PathPrefix(`/api/`) || PathPrefix(`/admin`) || PathPrefix(`/bundles/`) || PathPrefix(`/images/`))"
            - "traefik.http.routers.charges-api-tls.entrypoints=websecure"
            - "traefik.http.routers.charges-api-tls.priority=100"
            - "traefik.http.routers.charges-api-tls.tls=true"
            - "traefik.http.routers.charges-api-tls.tls.certresolver=le"
            - "traefik.http.routers.charges-api-tls.middlewares=charges-rewrite-api"
            - "traefik.http.routers.charges-api-tls.service=charges-api-tls"
            - "traefik.http.services.charges-api-tls.loadbalancer.server.port=80"
        networks:
            sepradcnetwork:
    db:
        image: mariadb:11.6
        platform: linux/arm64
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${MYSQL_DATABASE:-charges-website}
            MYSQL_USER: ${MYSQL_USER:-charges-user}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD:-charges-user}
            TZ: ${TZ:-Europe/Paris}
        volumes:
            - mysql_database:/var/lib/mysql
        # Port 3306 pas exposé publiquement en prod pour la sécurité
        cap_add:
            - SYS_NICE
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
            interval: 30s
            timeout: 10s
            retries: 3
        networks:
            sepradcnetwork:
    front:
        image: registry.sepradc.ovh/charge/front:arm64
        platform: linux/arm64
        restart: unless-stopped
        environment:
            NUXT_PUBLIC_API_BASE_URL: "https://${HOST}/api"
        healthcheck:
            test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://127.0.0.1:80"]
            interval: 30s
            timeout: 10s
            retries: 3
            start_period: 40s
        labels:
            - "traefik.enable=true"
            - "traefik.docker.network=sepradcnetwork"
            # Middlewares spécifiques à charges-website front
            - "traefik.http.middlewares.charges-front-https.redirectscheme.scheme=https"
            - "traefik.http.middlewares.charges-front-https.redirectscheme.permanent=true"
            # http://${HOST} : Redirect to https
            - "traefik.http.routers.charges-front.rule=Host(`${HOST}`)"
            - "traefik.http.routers.charges-front.entrypoints=web"
            - "traefik.http.routers.charges-front.middlewares=charges-front-https"
            - "traefik.http.routers.charges-front.service=charges-front"
            - "traefik.http.services.charges-front.loadbalancer.server.port=80"
            # https://${HOST}
            - "traefik.http.routers.charges-front-tls.rule=Host(`${HOST}`)"
            - "traefik.http.routers.charges-front-tls.entrypoints=websecure"
            - "traefik.http.routers.charges-front-tls.tls=true"
            - "traefik.http.routers.charges-front-tls.tls.certresolver=le"
            - "traefik.http.routers.charges-front-tls.service=charges-front-tls"
            - "traefik.http.services.charges-front-tls.loadbalancer.server.port=80"
        networks:
            sepradcnetwork:

volumes:
    mysql_database:
    caddy_data:
    caddy_config:

networks:
    sepradcnetwork:
        external: true
