version:  '3.8'
services:
    caddy:
        image: caddy:2.4.6-alpine
        restart: unless-stopped
        ports:
            # HTTP
            - target: 80
              published: 80
              protocol: tcp
            # HTTPS
            - target: 443
              published: 443
              protocol: tcp
            # HTTP/3
            - target: 443
              published: 443
              protocol: udp
        volumes:
            - ./docker/caddy:/etc/caddy
            - ./docker/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
            - ./api/public/:/var/www/public/
            - caddy_data:/data
            - caddy_config:/config
            - ./docker/caddy/status_pages/:/usr/share/caddy/status_pages/
        environment:
                HOST: $HOST
    api:
        build:
            context: .
            target: local
            dockerfile: docker/api/Dockerfile
        depends_on:
            - db
        volumes:
            - ./api:/var/www
        environment:
            HOST: ${HOST}
            XDEBUG_SESSION: debug-local
            PHP_IDE_CONFIG: serverName=api.sepradc.local
            XDEBUG_CLIENT_HOST: ${XDEBUG_CLIENT_HOST:-127.17.0.1}
            APP_UID: ${APP_UID:-1000}
    db:
        image: mariadb:10.5.5
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${MYSQL_DATABASE:-charges-website}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
            TZ: ${TZ:-Europe/Paris}
        volumes:
            - mysql_database:/var/lib/mysql
        ports:
            - 3306:3306
        cap_add:
            - SYS_NICE
    front:
        build:
            target: base
            context: .
            dockerfile: docker/front/Dockerfile
        ports:
            - "24678:24678"
        volumes:
            - ./front:/srv/app
volumes:
    mysql_database:
    caddy_data:
    caddy_config:


